<?php

function experience_help($path, $arg)
{
    if ($path == 'admin/help#experience') {
        return t('eXperience Online.');
    }
}

function experience_menu()
{
    $items['admin/settings/experience'] = array(
        'title' => 'eXperience Online',
        'description' => 'Beschreibung',
    );
    return $items;
}

/**
 * Implements hook_block_info().
 */
function experience_block_info()
{
    $blocks = array();
    $blocks['list_modules'] = array(
        'info' => t('eXperience Online: A listing of all of the enabled modules.'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function experience_block_view($block_name = '')
{
    if ($block_name == 'list_modules') {
        $list = module_list();
        #echo"<pre>";print_r($list);echo"</pre>";
        $theme_args = array('items' => $list, 'type' => 'ol');
        $content = theme('item_list', $theme_args);
        $block = array(
            'subject' => t('eXperience Online: Enabled Modules'),
            'content' => $content,
        );
        return $block;
    }
}   